# Generated by Django 3.1 on 2020-09-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List_Birthdays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_birthdays',
            name='age',
            field=models.IntegerField(),
        ),
    ]
