# Generated by Django 3.1 on 2020-09-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List_Birthdays', '0003_auto_20200906_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab_birthdays',
            options={'verbose_name_plural': 'Tab_Birthdays'},
        ),
        migrations.AlterField(
            model_name='tab_birthdays',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
