# Generated by Django 3.1 on 2020-09-10 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('List_Birthdays', '0004_auto_20200908_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_birthdays',
            name='dob_current_year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tab_birthdays',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
